### ISSUE TITLE
✨ Feat: CI/CD with Docker and Docker Compose

### ISSUE THREAD

**Issue by jun9898** [Boongeo/half-time-backend#12]
### 📄 Description
CI/CD 파이프라인을 Docker와 Docker Compose를 사용하여 구현. 애플리케이션을 컨테이너화하고, Docker Hub(또는 Docker Repository)를 활용해 이미지 관리를 자동화.

- **CI**: 코드 push 시 Docker 이미지를 빌드하고 Docker Hub에 push.
- **CD**: 최신 이미지를 자동으로 Pull하여 배포 환경에서 컨테이너를 업데이트.
- **Docker Compose**: 여러 서비스를 통합 관리.

### ✔️ TO-DO
- [x] CI 파이프라인 설정
  - [x] Docker 이미지 빌드 및 태깅
  - [x] Docker Hub에 이미지 푸시 (Docker Repository 설정)
  - [x] GitHub Actions 또는 GitLab CI 설정
- [x] CD 파이프라인 설정
  - [x] 배포 환경에서 Docker Compose를 통한 자동 배포 설정
  - [x] 최신 이미지 Pull 및 컨테이너 재시작 스크립트 작성
- [x] `docker-compose.yml` 작성
  - [x] 애플리케이션 서비스 정의
  - [x] Database, Redis 등 의존 서비스 추가
  - [x] 환경 변수 및 네트워크 설정
- [x] Dockerfile 작성
  - [x] Node.js/NestJS 기반의 Dockerfile 작성
  - [x] 멀티스테이지 빌드를 활용하여 최적화

### 🔔 ETC
- 우선 Dev 서버만 설정. 추후 production 환경 구축 완료하면 마찬가지로 파이프라인 수정할예정
