### ISSUE TITLE
✨ Feat: ProfileImage 저장 로직 추가

### ISSUE THREAD

**Issue by jun9898** [Boongeo/half-time-backend#13]
### 📄 Description  
NestJS에서 `upload` 디렉터리를 사용하여 정적 파일을 제공하는 기능을 도커 환경과 연계하여 안전하게 관리하고, 상대경로를 반환하도록 구현.

### ✔️ TO-DO  
- [x] `upload` 디렉터리를 Docker Compose로 볼륨 마운트 설정.  
- [x] `fs.writeFileSync`를 절대경로로 설정하여 안전하게 파일 저장.  
- [x] 업로드된 파일의 상대경로(`/uploads/...`)를 API 응답으로 반환.  
- [x] `express.static`을 사용해 정적 파일을 `/uploads/...` 경로로 제공.  
- [x] Docker 환경에서 `upload` 디렉터리가 로컬과 동기화되도록 확인.  

### 🔔 ETC   
- AWS S3 확장 가능성 고려해 설계
