### ISSUE TITLE
✨ Feat: CRUD 보일러 플레이트 작성

### ISSUE THREAD

**Issue by jun9898** [Boongeo/half-time-backend#6]
### 📄 Description  
- Board 도메인을 기반으로 보일러 플레이트 작성.  
- 페이징 인터셉터와 Swagger 적용.  

### ✔️ TO-DO  
- [x] Board Repository 작성.  
- [x] 페이징 인터셉터 설계 및 구현.  
- [x] Swagger를 활용한 API 명세 작성.  
- [x] CRUD API 작성 및 기능 검증.  

### 🔔 ETC  
- 공통 패턴 및 유틸리티 작성.
